<?xml version="1.0" encoding="utf-8"?>

<xs:schema id="Dir" targetNamespace="urn:schemas-fast-com:mobile-dir" elementFormDefault="qualified" xmlns="urn:schemas-fast-com:mobile-dir" xmlns:a="urn:schemas-fast-com:mobile-dir" xmlns:mstns="urn:schemas-fast-com:mobile-dir" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dir" type ="dirType">
    <xs:key name="field">
      <xs:selector xpath="a:fields/a:field" />
      <xs:field xpath="@name"/>
    </xs:key>
    <xs:key name="command">
      <xs:selector xpath="a:commands/a:command" />
      <xs:field xpath="@event" />
    </xs:key>
  </xs:element>

  <xs:complexType name="dirType">
    <xs:all maxOccurs="1" minOccurs="1">
      <xs:element name="title" type="headerType">
        <xs:annotation>
          <xs:documentation>View title displayed in the user interface.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="partition" type="partitionType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Data is contained in one or more partitions.</xs:documentation>
        </xs:annotation>
      </xs:element>

      <xs:element name="fields">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="field" type="fieldType" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="views" type="viewType" minOccurs="0" maxOccurs="1"/>

      <xs:element name="commands" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="command" type="commandType">
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="response" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="action" type="actionType">
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scripts" type="scriptType" minOccurs="0" maxOccurs="1"/>
    </xs:all>

    <xs:attribute name="type" type="appType" use="optional"/>
    <xs:attribute name="database" type="databaseName" use="optional"/>
    <xs:attribute name="data" type="xs:integer" use="optional"/>
    <xs:attribute name="detail" type="xs:integer" use="optional"/>
    <xs:attribute name="table" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>Specifies the name of the table</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="code" type="xs:string" use="optional"/>
    <xs:attribute name="name" type="xs:string" use="optional">
      <xs:annotation>
        <xs:documentation>You can use %l or %e placed after the value</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="filter" type="xs:string" use="optional"/>
    <xs:attribute name="valid" type="xs:string" use="optional"/>
    <xs:attribute name="check" type="xs:boolean" use="optional"/>
    <xs:attribute name="uniKey" type="xs:boolean" use="optional"/>
    <xs:attribute name="order" type="xs:string" use="optional"/>
    <xs:attribute name="id" type="xs:string" use="optional"/>
    <xs:attribute name="navigation" type="xs:boolean" use="optional"/>
    <xs:attribute name="cache" type="xs:boolean" use="optional"/>
    <xs:attribute name="scatter" type="xs:string" use="optional"/>
    <xs:attribute name="copyMode" type="xs:boolean" use="optional"/>
    <xs:attribute name="reference" type="xs:string" use="optional"/>
    <xs:attribute name="clearMode" type="xs:boolean" use="optional"/>
    <xs:attribute name="selectMode" type="xs:boolean" use="optional"/>
  </xs:complexType>

  <xs:complexType name="headerType">
    <xs:attribute name="v" type="xs:string" use="required"/>
    <xs:attribute name="e" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="fieldType">
    <xs:all maxOccurs="1" minOccurs="1">
      <xs:element name="header" type="headerType"  minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Specifies a default caption displayed in the form.</xs:documentation>
        </xs:annotation>
      </xs:element>

      <xs:element name="footer" type="headerType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Defines an extended field description displayed under the field in the form view.</xs:documentation>
        </xs:annotation>
      </xs:element>

      <xs:element name="label" type="headerType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Specifies a default text label displayed in the corresponding data fields of presentation views.</xs:documentation>
        </xs:annotation>
      </xs:element>

      <xs:element name="items" type="itemsType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="query" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="clientScript" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="request" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="field" type="xs:string" use="required"/>
          <xs:attribute name="action" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="script" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required"/>
          <xs:attribute name="onCopy" type="xs:boolean" use="optional"/>
          <xs:attribute name="detail" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="keys" type="keysType" minOccurs="0" maxOccurs="1"/>
    </xs:all>

    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>Matches the name of the column in the result set returned by query.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="aliasName" type="xs:string" use="optional"/>
    <xs:attribute name="cacheName" type="xs:string" use="optional"/>
    <xs:attribute name="condition" type="xs:string" use="optional"/>
    <xs:attribute name="type" type="dataType" use="optional">
      <xs:annotation>
        <xs:documentation>Specifies the data type of the base column of this field.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="isPrimaryKey" type="xs:boolean" use="optional" default="false">
      <xs:annotation>
        <xs:documentation>Indicates if the field is based on the primary key column.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="onDemand" type="xs:boolean" use="optional"/>
    <xs:attribute name="align" type="xs:string" use="optional"/>
    <xs:attribute name="width" type="xs:int" use="optional"/>
    <xs:attribute name="maxLength" type="xs:int" use="optional"/>
    <xs:attribute name="dataFormatString" type="xs:string" use="optional"/>
    <xs:attribute name="hyperlinkFormatString" type="xs:string" use="optional"/>
    <xs:attribute name="columns" type="xs:int" use="optional">
      <xs:annotation>
        <xs:documentation>Specifies the number of columns in the text box when the field is presented for editing.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="rows" type="xs:int" use="optional">
      <xs:annotation>
        <xs:documentation>Specifies the number of rows in the text box when the field is presented for editing.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="categoryIndex" type="xs:int" use="optional"/>
    <xs:attribute name="readOnly" type="xs:boolean" use="optional" default="false">
      <xs:annotation>
        <xs:documentation>Indicates if the field is read-only.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="inactivate" type="xs:boolean" use="optional"/>
    <xs:attribute name="hidden" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Hides the data field from user interface rendered in client browser. Hidden fields can be modified in custom action handlers.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="disable" type="xs:boolean" use="optional"/>

    <xs:attribute name="textAlignment" type="a:textAlignType" use="optional"/>
    <xs:attribute name="check" type="xs:string" use="optional"/>
    <xs:attribute name="internal" type="xs:boolean" use="optional"/>
    <xs:attribute name="onFocus" type="xs:string" use="optional"/>
    <xs:attribute name="targetName" type="xs:string" use="optional"/>
    <xs:attribute name="sqlType" type="xs:string" use="optional"/>
    <xs:attribute name="sqlValue" type="xs:string" use="optional"/>

    <xs:attribute name="allowContain" type="xs:boolean" use="optional" default="false">
      <xs:annotation>
        <xs:documentation>Indicates if the field is allowed values that contain each other.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="allowQBE" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Controls if the query-by-example is allowed in the column of the form view. Default value is 'true'.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="allowSorting" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Controls is sorting is allowed in the column of the form view.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="allowFilter" type="xs:boolean" use="optional"/>
    <xs:attribute name="allowNulls" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Default value is 'true'.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="defaultValue" type="xs:string" use="optional"/>
    <xs:attribute name="clientDefault" type="xs:string" use="optional"/>
    <xs:attribute name="when" type="xs:boolean" use="optional"/>

    <xs:attribute name="external" type="xs:boolean" use="optional">
      <xs:annotation>
        <xs:documentation>Specifies the external field does not exist in table. External fields can not be updated.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="operation" type="xs:string" use="optional"/>
    <xs:attribute name="filterSource" type="xs:string" use="optional"/>
    <xs:attribute name="allowRequest" type="xs:boolean" use="optional"/>
    <xs:attribute name="push" type="xs:boolean" use="optional"/>

    <xs:attribute name="min" type="xs:string" use="optional"/>
    <xs:attribute name="max" type="xs:string" use="optional"/>
    <xs:attribute name="apiKey" type="xs:string" use="optional"/>
    <xs:attribute name="media" type="xs:boolean" use="optional"/>
  </xs:complexType>

  <xs:complexType name="partitionType">
    <xs:all maxOccurs="1" minOccurs="1"/>
    <xs:attribute name="table" type="xs:string" use="required"/>
    <xs:attribute name="prime" type="xs:string" use="required"/>
    <xs:attribute name="inquiry" type="xs:string" use="optional"/>
    <xs:attribute name="field" type="xs:string" use="required"/>
    <xs:attribute name="expression" type="xs:string" use="required"/>
    <xs:attribute name="increase" type="xs:string" use="optional"/>
    <xs:attribute name="default" type="xs:string" use="required"/>
    <xs:attribute name="condition" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="commandType">
    <xs:sequence>
      <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Defines the command text that corresponds to the command type.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>

    <xs:attribute name="event" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Initialize"/>
          <xs:enumeration value="Created"/>
          <xs:enumeration value="Declare"/>
          <xs:enumeration value="Loading"/>
          <xs:enumeration value="Scattering"/>
          <xs:enumeration value="Navigating"/>
          <xs:enumeration value="Showing"/>
          <xs:enumeration value="Inserting"/>
          <xs:enumeration value="Inserted"/>
          <xs:enumeration value="Updating"/>
          <xs:enumeration value="Updated"/>
          <xs:enumeration value="Copying"/>
          <xs:enumeration value="Deleting"/>
          <xs:enumeration value="Deleted"/>
          <xs:enumeration value="Checking"/>
          <xs:enumeration value="Querying"/>
          <xs:enumeration value="Processing"/>
          <xs:enumeration value="Closing"/>
          <xs:enumeration value="Result"/>

          <xs:enumeration value="InitExternalFields"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="database" type="databaseName" use="optional"/>
  </xs:complexType>

  <xs:complexType name="scriptType">
    <xs:sequence>
      <xs:element name="script" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="optional"/>
          <xs:attribute name="field" type="xs:string" use="optional"/>
          <xs:attribute name="method" type="xs:string" use="optional"/>
          <xs:attribute name="return" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="itemsType">
    <xs:sequence>
      <xs:element name="item" type ="itemType" minOccurs="0" maxOccurs="unbounded">
      </xs:element>
    </xs:sequence>
    <xs:attribute name="style" use="required">
      <xs:annotation>
        <xs:documentation>Specifies a presentation style of field items.</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Toggle"/>
          <xs:enumeration value="AutoComplete"/>
          <xs:enumeration value="Lookup"/>

          <xs:enumeration value="Numeric"/>
          <xs:enumeration value="Mask"/>
          <xs:enumeration value="Grid"/>
          <xs:enumeration value="CheckBox"/>
          <xs:enumeration value="DropDownList"/>
          <xs:enumeration value="ListBox"/>
          <xs:enumeration value="RadioButtonList"/>

          <xs:enumeration value="TextUnderLine"/>
          <xs:enumeration value="Hour"/>
          <xs:enumeration value="Tax"/>
          <xs:enumeration value="Password"/>
          <xs:enumeration value="Captcha"/>
          <xs:enumeration value="Email"/>
          <xs:enumeration value="FileUpload"/>
          <xs:enumeration value="Script"/>
          <xs:enumeration value="Location"/>
          <xs:enumeration value="BioPassword"/>
          <xs:enumeration value="Video"/>
          <xs:enumeration value="Image"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="table" type="xs:string" use="optional"/>
    <xs:attribute name="code" type="xs:string" use="optional"/>
    <xs:attribute name="orderBy" type="xs:string" use="optional"/>
    <xs:attribute name="database" type="databaseName" use="optional"/>
    <xs:attribute name="controller" type="xs:string" use="optional"/>
    <xs:attribute name="reference" type="xs:string" use="optional"/>
    <xs:attribute name="key" type="xs:string" use="optional"/>
    <xs:attribute name="check" type="xs:string" use="optional"/>
    <xs:attribute name="new" type="xs:string" use="optional"/>
    <xs:attribute name="row" type="xs:int" use="optional"/>
    <xs:attribute name="normal" type="xs:boolean" use="optional"/>
    <xs:attribute name="information" type="xs:string" use="optional"/>
    <xs:attribute name="input" type="xs:string" use="optional"/>
    <xs:attribute name="allowNulls" type="xs:boolean" use="optional"/>
    <xs:attribute name="push" type="xs:boolean" use="optional"/>
    <xs:attribute name="annotation" type="xs:boolean" use="optional"/>
    <xs:attribute name="moveMode" type="xs:string" use="optional"/>
    <xs:attribute name="near" type="xs:boolean" use="optional"/>
    <xs:attribute name="address" type="xs:boolean" use="optional"/>
    <xs:attribute name="type" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="itemType">
    <xs:all maxOccurs="1" minOccurs="1">
      <xs:element name="text" type="headerType"/>
    </xs:all>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="actionType">
    <xs:sequence>
      <xs:element name="text" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="database" use="optional" type="databaseName"/>
  </xs:complexType>

  <xs:complexType name="viewType">
    <xs:sequence>
      <xs:element name="view" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="header" type="headerType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="row"  minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="width" type="xs:string" use="optional"/>
                <xs:attribute name="value" type="xs:string" use="optional"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>

          <xs:attribute name="id" type="xs:string" use="optional"/>
          <xs:attribute name="line" type="xs:boolean" use="optional"/>
          <xs:attribute name="isExpand" type="xs:boolean" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="textAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Start"/>
      <xs:enumeration value="Center"/>
      <xs:enumeration value="End"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dataType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AnsiString"/>
      <xs:enumeration value="Binary"/>
      <xs:enumeration value="Byte"/>
      <xs:enumeration value="Boolean"/>
      <xs:enumeration value="Currency"/>
      <xs:enumeration value="Date"/>
      <xs:enumeration value="DateTime"/>
      <xs:enumeration value="Decimal"/>
      <xs:enumeration value="Double"/>
      <xs:enumeration value="Guid"/>
      <xs:enumeration value="Int16"/>
      <xs:enumeration value="Int32"/>
      <xs:enumeration value="Int64"/>
      <xs:enumeration value="Object"/>
      <xs:enumeration value="SByte"/>
      <xs:enumeration value="Single"/>
      <xs:enumeration value="String"/>
      <xs:enumeration value="Time"/>
      <xs:enumeration value="UInt16"/>
      <xs:enumeration value="UInt32"/>
      <xs:enumeration value="UInt64"/>
      <xs:enumeration value="VarNumeric"/>
      <xs:enumeration value="Numeric"/>
      <xs:enumeration value="AnsiStringFixedLength"/>
      <xs:enumeration value="StringFixedLength"/>
      <xs:enumeration value="Xml"/>
      <xs:enumeration value="DateTime2"/>
      <xs:enumeration value="DateTimeOffset"/>
      <xs:enumeration value="Byte[]"/>

      <xs:enumeration value="Toggle"/>
      <xs:enumeration value="Table"/>
      <xs:enumeration value="Char"/>
      <xs:enumeration value="Bool"/>
      <xs:enumeration value="Dir"/>
      <xs:enumeration value="Edit"/>
      <xs:enumeration value="Map"/>
      <xs:enumeration value="Media"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="appType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Dir"/>
      <xs:enumeration value="Report"/>
      <xs:enumeration value="Voucher"/>
      <xs:enumeration value="Detail"/>

      <xs:enumeration value="Approval"/>
      <xs:enumeration value="Account"/>
      <xs:enumeration value="Inquiry"/>
      <xs:enumeration value="Filter"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="keysType">
    <xs:sequence>
      <xs:element name="key" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="name" type="xs:string" use="optional"/>
          <xs:attribute name="value" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="databaseName">
    <xs:restriction base="xs:string">
      <xs:enumeration value="App"/>
      <xs:enumeration value="Sys"/>
      <xs:enumeration value="Ext"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>